"""Cambios de Modulo Ajuste inventario modificados

Revision ID: 0af413076517
Revises: 288703a7599a
Create Date: 2026-06-06 16:27:27.169139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af413076517'
down_revision = '288703a7599a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajuste_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_ajuste', sa.Integer(), nullable=False))
        batch_op.drop_column('cantidad_ajustada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajuste_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_ajustada', sa.INTEGER(), nullable=False))
        batch_op.drop_column('cantidad_ajuste')

    # ### end Alembic commands ###
