"""Cambios de Archivo models.py en Clientes

Revision ID: 288703a7599a
Revises: 8cec25f773cf
Create Date: 2026-06-05 18:18:48.217069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288703a7599a'
down_revision = '8cec25f773cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
