"""Modelos DB coregidos

Revision ID: 8cec25f773cf
Revises: fb4501a982e1
Create Date: 2026-06-05 10:09:49.969931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cec25f773cf'
down_revision = 'fb4501a982e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ci_nit', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('ci_nit')
    )
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nombre_material', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_material'),
    sa.UniqueConstraint('nombre_material')
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_razon_social', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('joya',
    sa.Column('id_joya', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ),
    sa.PrimaryKeyConstraint('id_joya'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('ajuste_inventario',
    sa.Column('id_ajuste', sa.Integer(), nullable=False),
    sa.Column('id_joya', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_ajuste', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cantidad_ajustada', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('tipo_ajuste', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_joya'], ['joya.id_joya'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ajuste')
    )
    op.create_table('detalle_compra',
    sa.Column('id_det_compra', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_joya', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unit_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id_compra'], ),
    sa.ForeignKeyConstraint(['id_joya'], ['joya.id_joya'], ),
    sa.PrimaryKeyConstraint('id_det_compra')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_joya', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unit_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_joya'], ['joya.id_joya'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_table('detalle_compra')
    op.drop_table('ajuste_inventario')
    op.drop_table('venta')
    op.drop_table('joya')
    op.drop_table('compra')
    op.drop_table('proveedor')
    op.drop_table('material')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
