"""Modelos de la DB definidos

Revision ID: fb4501a982e1
Revises: d26dcaa34ba2
Create Date: 2026-06-05 09:51:21.526997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4501a982e1'
down_revision = 'd26dcaa34ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=False))
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
